# Generated by Django 2.2.1 on 2019-06-07 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_auto_20190607_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_justificativa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - A justificativa é clara e fundamentada? (1,0)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_metodologia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - Os aspectos metodológicos do projeto envolvem os objetivos propostos? (1,0)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Mérito do projeto - A pesquisa resultará em impacto importante IES e tem perfil de agregar novos alunos ao Curso Stricto Sensu? (2,0)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_relevancia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - O projeto apresentado tem caráter científico-investigativo e interdisciplinar, configurando um projeto de pesquisa? (1,0)'),
        ),
    ]
