# Generated by Django 2.2.1 on 2019-06-07 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_auto_20190607_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_eventos_anais_completo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.4)], verbose_name='Atividades Científicas 2015-2018 - Trabalho completo em anais de evento (0,4): primeiro ou último autor (0,05), demais posições (0,01)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_revista_internacional',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Atividades Científicas 2015-2018 - Publicação em revista internacional (1,0): primeiro ou último ator (0,4), demais posições (0,15)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_revista_nacional',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Atividades Científicas 2015-2018 - Publicação em revista nacional com Qualis (1,0): primeiro ou último autor: (0,15), demais posições (0,05) '),
        ),
    ]
