# Generated by Django 2.2.1 on 2019-06-07 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_auto_20190607_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_alunos_IC',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.3)], verbose_name='Atividades Científicas 2015-2018 - O orientador tem experiência prévia em orientação de alunos de iniciação científica (0,3): por aluno(0,1)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_eventos_resumos',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.3)], verbose_name='Atividades Científicas 2015-2018 - Resumos em eventos (0,3): primeiro ou último autor(0,02), demais posições(0,01)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_livros',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.3)], verbose_name='Atividades Científicas 2015-2018 - Livros (0,3): capitulo de livros(0,1), livro completo(0,2)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_projeto_fomento',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.2)], verbose_name='Atividades Científicas 2015-2018 - O orientador tem projeto aprovado em agência de fomento? (0,2)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_strict_sisu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='Atividades Científicas 2015-2018 - O orientador está vinculado à Programa de Pós-Graduação Stricto Sensu? (0,5)'),
        ),
    ]
