# Generated by Django 2.2.1 on 2019-06-07 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0005_auto_20190607_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='bolsista_media_notas',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Bolsista - Média das notas do aluno nas disciplinas cursadas (1,5)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='bolsista_nivel_curso',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='Bolsista - Nível em que o aluno se encontra no curso (0,5): segundo e terceiro semestre (0,2), a partir do quarto semestre (0,5)'),
        ),
    ]
