# Generated by Django 2.2.1 on 2019-06-12 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0006_auto_20190607_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_alunos_IC',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.3)], verbose_name='Atividades Científicas 2015-2018 - O orientador tem experiência prévia em orientação de alunos de iniciação científica (máximo 0.3 pontos): por aluno (0.1)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_eventos_anais_completo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.4)], verbose_name='Atividades Científicas 2015-2018 - Trabalho completo em anais de evento (máximo 0.4 pontos): primeiro ou último autor (0.05), demais posições (0.01)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_eventos_resumos',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.3)], verbose_name='Atividades Científicas 2015-2018 - Resumos em eventos (máximo 0.3 pontos): primeiro ou último autor (0.02), demais posições (0.01)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_livros',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.3)], verbose_name='Atividades Científicas 2015-2018 - Livros (máximo 0.3 pontos): capitulo de livros (0.1), livro completo (0.2)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_projeto_fomento',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.2)], verbose_name='Atividades Científicas 2015-2018 - O orientador tem projeto aprovado em agência de fomento? (máximo 0.2 pontos)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_revista_internacional',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Atividades Científicas 2015-2018 - Publicação em revista internacional (máximo 1.0 ponto): primeiro ou último ator (0.4), demais posições (0.15)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_revista_nacional',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Atividades Científicas 2015-2018 - Publicação em revista nacional com Qualis (máximo 1.0 ponto): primeiro ou último autor: (0.15), demais posições (0.05) '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_strict_sisu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='Atividades Científicas 2015-2018 - O orientador está vinculado à Programa de Pós-Graduação Stricto Sensu? (máximo 0.5 pontos)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='bolsista_media_notas',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Bolsista - Média das notas do aluno nas disciplinas cursadas (máximo 1.5 pontos)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='bolsista_nivel_curso',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='Bolsista - Nível em que o aluno se encontra no curso (máximo 0.5 pontos): segundo e terceiro semestre (0.2), a partir do quarto semestre (0.5)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_justificativa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - A justificativa é clara e fundamentada? (máximo 1.0 ponto)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_metodologia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - Os aspectos metodológicos do projeto envolvem os objetivos propostos? (máximo 1.0 ponto)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Mérito do projeto - A pesquisa resultará em impacto importante IES e tem perfil de agregar novos alunos ao Curso Stricto Sensu? (máximo 2.0 pontos)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_relevancia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - O projeto apresentado tem caráter científico-investigativo e interdisciplinar, configurando um projeto de pesquisa? (máximo 1.0 ponto)'),
        ),
    ]
