# Generated by Django 2.2.1 on 2019-06-12 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_auto_20190612_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_justificativa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - A justificativa é clara e tem relevância científica? (máximo 1.0 ponto)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - O plano de trabalho do bolsista contempla o projeto apresentado? (máximo 1.0 ponto)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_relevancia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - O projeto apresentado tem caráter científico-investigativo e interdisciplinar, configurando um projeto de iniciação científica ou inovação tecnológica trazendo temas relevantes ou inovadores? (máximo 1.0 ponto)'),
        ),
    ]
