# Generated by Django 2.2.1 on 2019-06-12 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0010_auto_20190612_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_bolsista_CNPQ',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='Atividades Científicas 2015-2018 - O orientador é bolsista de produtividade CNPQ? (máximo 0.1 pontos)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_strict_sisu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='Atividades Científicas 2015-2018 - O orientador está vinculado à Programa de Pós-Graduação Stricto Sensu? (máximo 0.4 pontos)'),
        ),
    ]
