# Generated by Django 2.2.1 on 2019-06-19 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0011_auto_20190612_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_justificativa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - A justificativa apresenta sinergia do projeto com o modelo de negócios da empresa parceira e o potencial inovador e/ou mercadológico? máximo 1 ponto'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_metodologia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - Os aspectos metodológicos do projeto envolvem os objetivos propostos atendendo ao perfil de inovação tecnológica e/ou de mercado? '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - O plano de trabalho do bolsista contempla o projeto apresentado em consonância com a empresa parceira? máximo 1.0 ponto'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_relevancia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Mérito do projeto - O projeto apresentado tem caráter científico-investigativo, configurando um projeto de inovação tecnológica, trazendo temas relevantes ou inovadores com perfil de inovação e de mercado para a UFN? máximo 1 ponto'),
        ),
    ]
