# Generated by Django 2.2.2 on 2019-07-03 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0012_auto_20190619_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_alunos_IC',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_bolsista_CNPQ',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_eventos_anais_completo',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_eventos_resumos',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_livros',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_projeto_fomento',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_revista_internacional',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_revista_nacional',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='atividades_cientificas_orientador_strict_sisu',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a1_cinco_autores',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A1 até 5 autores'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a1_mais_cinco_autores_demais',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A1 com mais artigos até 5 autores: Demais posições de autoria'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a1_mais_cinco_autores_primeiro_ultimo',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A1 com mais de 5 autores: Primeiro ou último ator'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a2_cinco_autores',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A2 até 5 autores'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a2_mais_cinco_autores_demais',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A2 com mais artigos até 5 autores: Demais posições de autoria'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a2_mais_cinco_autores_primeiro_ultimo',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A2 com mais de 5 autores: Primeiro ou último ator'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b1_b2_cinco_autores',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B1 e B2 até 5 autores'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b1_b2_mais_cinco_autores_demais',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B1 e B2 com mais artigos até 5 autores: Demais posições de autoria'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b1_b2_mais_cinco_autores_primeiro_ultimo',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B1 e B2 com mais de 5 autores: Primeiro ou último ator'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b3_b4_cinco_autores',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B3 e B4 até 5 autores'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b3_b4_mais_cinco_autores_demais',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B3 e B4 com mais artigos até 5 autores: Demais posições de autoria'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b3_b4_mais_cinco_autores_primeiro_ultimo',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B3 e B4 com mais de 5 autores: Primeiro ou último ator'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b5_c_cinco_autores',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B5 e C até 5 autores'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b5_c_mais_cinco_autores_demais',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B3 e C com mais artigos até 5 autores: Demais posições de autoria'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b5_c_mais_cinco_autores_primeiro_ultimo',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B3 e C com mais de 5 autores: Primeiro ou último ator'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_autoria_livros',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de autoria de Livros Técnico/Científico com ISBN publicados em editora que possua ou Comitê, ou Comissão ou Conselho Editorial'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_autoria_livros_capitulos',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de capítulos e organização de Livros Técnico/Científico com ISBN publicados em editora que possua ou Comitê, ou Comissão ou Conselho Editorial'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_licenca_direito',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de licenças de direito de propriedade intelectual'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_orientador_iniciacao_cientifica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de orientações de Iniciação científica/Tecnológica na UFN em andamento ou concluída: limite 6'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_orientador_mestrado',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de dissertações de mestrado orientadas como orientador principal e aprovadas na UFN: limite 5'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_orientador_teses_doutorado',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de teses de doutorado orientadas como orientador principal e aprovadas na UFN: limite 5'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_orientador_trabalho_final_curso',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de orientações de Trabalho Final de Curso na UFN no estado concluído: limite 6'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_resumos_anais_eventos',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de resumos ou resumos expandidos publicados em anais de eventos: limite 10'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pc_trabalhos_anais_eventos',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de trabalhos completos em anais de eventos: limite 10'),
        ),
    ]
