# Generated by Django 2.2.2 on 2019-08-06 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0015_auto_20190710_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='merito_projeto_justificativa',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='merito_projeto_metodologia',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='merito_projeto_relevancia',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='merito_projeto_justificativa_responsavel',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='A justificativa apresenta sinergia do projeto com o modelo de negócios da empresa parceira e o potencial inovador e/ou mercadológico? máximo 1 ponto'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='merito_projeto_justificativa_suplente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='A justificativa apresenta sinergia do projeto com o modelo de negócios da empresa parceira e o potencial inovador e/ou mercadológico? máximo 1 ponto'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='merito_projeto_metodologia_responsavel',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Os aspectos metodológicos do projeto envolvem os objetivos propostos atendendo ao perfil de inovação tecnológica e/ou de mercado? '),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='merito_projeto_metodologia_suplente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Os aspectos metodológicos do projeto envolvem os objetivos propostos atendendo ao perfil de inovação tecnológica e/ou de mercado? '),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades_responsavel',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O plano de trabalho do bolsista contempla o projeto apresentado em consonância com a empresa parceira? máximo 1.0 ponto'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades_suplente',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O plano de trabalho do bolsista contempla o projeto apresentado em consonância com a empresa parceira? máximo 1.0 ponto'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='merito_projeto_relevancia_responsavel',
            field=models.IntegerField(blank=True, help_text='Máximo 1 ponto', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O projeto apresentado tem caráter científico-investigativo, configurando um projeto de inovação tecnológica, trazendo temas relevantes ou inovadores com perfil de inovação e de mercado para a UFN? máximo 1 ponto'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='merito_projeto_relevancia_suplente',
            field=models.IntegerField(blank=True, help_text='Máximo 1 ponto', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O projeto apresentado tem caráter científico-investigativo, configurando um projeto de inovação tecnológica, trazendo temas relevantes ou inovadores com perfil de inovação e de mercado para a UFN? máximo 1 ponto'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a1_mais_cinco_autores_demais',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A1 com mais artigos até 5 autores: Demais posições de autoria'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a1_mais_cinco_autores_primeiro_ultimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A1 com mais de 5 autores: Primeiro ou último ator'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a2_cinco_autores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A2 até 5 autores'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a2_mais_cinco_autores_demais',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A2 com mais artigos até 5 autores: Demais posições de autoria'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_a2_mais_cinco_autores_primeiro_ultimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis A2 com mais de 5 autores: Primeiro ou último ator'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b1_b2_cinco_autores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B1 e B2 até 5 autores'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b1_b2_mais_cinco_autores_demais',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B1 e B2 com mais artigos até 5 autores: Demais posições de autoria'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b1_b2_mais_cinco_autores_primeiro_ultimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B1 e B2 com mais de 5 autores: Primeiro ou último ator'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b3_b4_cinco_autores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B3 e B4 até 5 autores'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b3_b4_mais_cinco_autores_demais',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B3 e B4 com mais artigos até 5 autores: Demais posições de autoria'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b3_b4_mais_cinco_autores_primeiro_ultimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B3 e B4 com mais de 5 autores: Primeiro ou último ator'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b5_c_cinco_autores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B5 e C até 5 autores'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b5_c_mais_cinco_autores_demais',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B3 e C com mais artigos até 5 autores: Demais posições de autoria'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_artigos_qualis_b5_c_mais_cinco_autores_primeiro_ultimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de artigos Qualis B3 e C com mais de 5 autores: Primeiro ou último ator'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_autoria_livros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de autoria de Livros Técnico/Científico com ISBN publicados em editora que possua ou Comitê, ou Comissão ou Conselho Editorial'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_autoria_livros_capitulos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de capítulos e organização de Livros Técnico/Científico com ISBN publicados em editora que possua ou Comitê, ou Comissão ou Conselho Editorial'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_licenca_direito',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de licenças de direito de propriedade intelectual'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_orientador_iniciacao_cientifica',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de orientações de Iniciação científica/Tecnológica na UFN em andamento ou concluída: limite 6'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_orientador_mestrado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de dissertações de mestrado orientadas como orientador principal e aprovadas na UFN: limite 5'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_orientador_teses_doutorado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de teses de doutorado orientadas como orientador principal e aprovadas na UFN: limite 5'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_orientador_trabalho_final_curso',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de orientações de Trabalho Final de Curso na UFN no estado concluído: limite 6'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_resumos_anais_eventos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de resumos ou resumos expandidos publicados em anais de eventos: limite 10'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pc_trabalhos_anais_eventos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Produção Cientifíca dos últimos 3 anos - Quantidade de trabalhos completos em anais de eventos: limite 10'),
        ),
    ]
