# Generated by Django 2.2.2 on 2019-08-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0016_auto_20190805_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='dt_avaliacao_responsavel',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da avaliação do responsável'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='dt_avaliacao_suplente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da avaliação do suplente'),
        ),
    ]
