# Generated by Django 3.0.4 on 2020-05-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0018_auto_20200415_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EM ANÁLISE', 'Em análise'), ('EM EDIÇÃO', 'Em edição'), ('PENDENTE', 'Pendente'), ('PÓS CORREÇÃO', 'Pós correção')], max_length=25, verbose_name='Status do projeto'),
        ),
    ]
