# Generated by Django 3.0.4 on 2020-06-24 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0019_auto_20200527_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='bolsista_media_notas',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.5 ponto', max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Bolsista - Média das notas do aluno nas disciplinas cursadas'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='bolsista_nivel_curso',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 0.5 ponto: segundo e terceiro semestre (0.2), a partir do quarto semestre (0.5)', max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='Bolsista - Nível em que o aluno se encontra no curso'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_justificativa_responsavel',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='A justificativa apresenta sinergia do projeto com o modelo de negócios da empresa parceira e o potencial inovador e/ou mercadológico?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_justificativa_suplente',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='A justificativa apresenta sinergia do projeto com o modelo de negócios da empresa parceira e o potencial inovador e/ou mercadológico?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_metodologia_responsavel',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Os aspectos metodológicos do projeto envolvem os objetivos propostos atendendo ao perfil de inovação tecnológica e/ou de mercado?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_metodologia_suplente',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Os aspectos metodológicos do projeto envolvem os objetivos propostos atendendo ao perfil de inovação tecnológica e/ou de mercado?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades_responsavel',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O plano de trabalho do bolsista contempla o projeto apresentado em consonância com a empresa parceira?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades_suplente',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O plano de trabalho do bolsista contempla o projeto apresentado em consonância com a empresa parceira?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_relevancia_responsavel',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O projeto apresentado tem caráter científico-investigativo, configurando um projeto de inovação tecnológica, trazendo temas relevantes ou inovadores com perfil de inovação e de mercado para a UFN?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_relevancia_suplente',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O projeto apresentado tem caráter científico-investigativo, configurando um projeto de inovação tecnológica, trazendo temas relevantes ou inovadores com perfil de inovação e de mercado para a UFN?'),
        ),
    ]
