# Generated by Django 3.0.4 on 2020-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0020_auto_20200624_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='total_producoes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
    ]
