# Generated by Django 3.0.4 on 2020-07-02 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0023_auto_20200701_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='pontuacao_final_producoes',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='bolsista_media_notas',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Máximo 2.0 pontos', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Bolsista - Média das notas do aluno nas disciplinas cursadas'),
        ),
    ]
