# Generated by Django 3.0.4 on 2020-07-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0024_auto_20200702_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('EM ANÁLISE', 'Em análise'), ('EM EDIÇÃO', 'Em edição')], max_length=25, verbose_name='Status do projeto'),
        ),
    ]
