# Generated by Django 3.0.4 on 2020-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0025_auto_20200706_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='arquivo_parecer_final',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo com parecer final'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EM ANÁLISE', 'Em análise'), ('EM EDIÇÃO', 'Em edição')], default='EM ANÁLISE', max_length=25, verbose_name='Status do projeto'),
        ),
    ]
