# Generated by Django 3.0.4 on 2020-07-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0026_auto_20200706_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='arquivo_parecer_final',
            field=models.FileField(default=None, help_text='Use arquivo .pdf para a resposta', upload_to='midias', verbose_name='Arquivo com parecer final'),
            preserve_default=False,
        ),
    ]
