# Generated by Django 3.0.4 on 2020-07-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0027_auto_20200706_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='arquivo_parecer_final',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo com parecer SADEPI'),
        ),
    ]
