# Generated by Django 3.0.4 on 2020-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0030_remove_avaliacao_arquivo_parecer_comissao_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('EM ANÁLISE', 'Em análise'), ('EM EDIÇÃO', 'Em edição')], default='EM ANÁLISE', max_length=25, verbose_name='Status do projeto'),
        ),
    ]
