# Generated by Django 3.0.8 on 2020-07-22 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0031_auto_20200707_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_relevancia_suplente',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O projeto apresentado tem caráter científico-investigativo, configurando um projeto de inovação tecnológica, trazendo temas relevantes ou inovadores com perfil de inovação e de mercado para a UFN?'),
        ),
    ]
