# Generated by Django 3.0.4 on 2020-09-02 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0026_submissao_area_tecnologica'),
        ('avaliacao', '0032_auto_20200722_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['submissao', 'comissao__status']},
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='status',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_justificativa_responsavel',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='A justificativa é clara e tem relevância científica?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_justificativa_suplente',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='A justificativa é clara e tem relevância científica?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_metodologia_responsavel',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Os aspectos metodológicos do projeto envolvem os objetivos propostos?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_metodologia_suplente',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1 ponto', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Os aspectos metodológicos do projeto envolvem os objetivos propostos?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades_responsavel',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O plano de atividades do bolsista contempla o projeto apresentado?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_plano_atividades_suplente',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O plano de atividades do bolsista contempla o projeto apresentado?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_relevancia_responsavel',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O projeto apresentado tem caráter científico-investigativo, configurando um projeto de iniciação científica ou de inovação tecnológica, trazendo temas relevantes ou inovadores?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='merito_projeto_relevancia_suplente',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Máximo 1.0 ponto', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='O projeto apresentado tem caráter científico-investigativo, configurando um projeto de iniciação científica ou de inovação tecnológica, trazendo temas relevantes ou inovadores?'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='submissao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='submissao.Submissao', verbose_name='Selecione um projeto submetido para avaliação *'),
        ),
    ]
