# Generated by Django 2.1.2 on 2018-12-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0003_auto_20181213_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='abertura',
            field=models.DateField(null=True, verbose_name='Abertura do edital'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='encerra',
            field=models.DateField(null=True, verbose_name='Encerramento do edital'),
        ),
    ]
