# Generated by Django 2.1.2 on 2018-12-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0004_auto_20181213_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='abertura',
            field=models.CharField(max_length=14, null=True, verbose_name='Abertura do edital'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='encerra',
            field=models.CharField(max_length=14, null=True, verbose_name='Encerramento do edital'),
        ),
    ]
