# Generated by Django 2.1.2 on 2018-12-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0008_auto_20181213_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='abertura',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='encerra',
        ),
    ]
