# Generated by Django 2.1.2 on 2018-12-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0009_auto_20181213_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Abertura do edital'),
        ),
    ]
