# Generated by Django 2.1.2 on 2018-12-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0010_edital_abertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='encerra',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Encerramento do edital'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='abertura',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Abertura do edital'),
        ),
    ]
