# Generated by Django 2.1.2 on 2019-03-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0013_auto_20181213_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='bolsista',
            field=models.BooleanField(blank=True, default=False, help_text='Se marcado então há bolsista no edital', verbose_name='bolsista'),
        ),
    ]
