# Generated by Django 2.1.2 on 2019-04-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0014_edital_bolsista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='abertura',
            field=models.DateField(blank=True, help_text='dd/mm/aaaa', null=True, verbose_name='Abertura do edital'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='encerra',
            field=models.DateField(blank=True, help_text='dd/mm/aaaa', null=True, verbose_name='Encerramento do edital'),
        ),
    ]
