# Generated by Django 2.2.2 on 2019-07-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0015_auto_20190411_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='link_edital',
            field=models.URLField(blank=True, help_text='Seção de editais do site UFN', verbose_name='Link do edital no site UFN'),
        ),
    ]
