# Generated by Django 3.0.4 on 2020-06-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgao', '0001_initial'),
        ('edital', '0018_edital_orgao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgao.Orgao', verbose_name='Órgão de Fomento'),
        ),
    ]
