# Generated by Django 3.0.4 on 2020-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
        ('edital', '0019_auto_20200612_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='programa',
            field=models.ManyToManyField(blank=True, help_text='Para selecionar ou deselecionar um programa pressione CTRL + Botão Esquerdo do mouse ou Command + Botão Esquerdo do mouse', null=True, related_name='programa', to='programa.Programa', verbose_name='Programa(s) ou linha(s) de fomento'),
        ),
    ]
