# Generated by Django 2.1.2 on 2018-11-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
                ('site', models.CharField(max_length=100, verbose_name='Site instituição')),
            ],
            options={
                'ordering': ['sigla'],
            },
        ),
    ]
