# Generated by Django 2.2.1 on 2019-05-22 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edital', '0015_auto_20190411_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da empresa')),
                ('contato_empresa', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email da empresa')),
                ('area', models.CharField(choices=[('CIÊNCIAS DA SAÚDE', 'Ciências da Saúde'), ('CIÊNCIAS HUMANAS', 'Ciências Humanas'), ('CIÊNCIAS SOCIAIS', 'Ciências Sociais'), ('CIÊNCIAS TECNOLÓGICAS', 'Ciências Tecnológicas')], max_length=25, verbose_name='Área de ensino, pesquisa e extensão de execução do projeto')),
                ('titulo', models.TextField(max_length=200, verbose_name='Título do projeto (200 caracteres)')),
                ('introducao', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Introdução do projeto (2000 caracteres)')),
                ('palavras_chave', models.TextField(max_length=100, verbose_name='Palavras-chave: 3 a 5 expressões separadas por ponto-e-vírgula')),
                ('motivacao', models.TextField(max_length=2000, verbose_name='Motivação/Justificativa do projeto (2000 caracteres)')),
                ('objetivo', models.TextField(max_length=2000, verbose_name='Objetivos geral e específicos do projeto (2000 caracteres)')),
                ('metodologia', models.TextField(max_length=2000, verbose_name='Materiais e Métodos do projeto (2000 caracteres)')),
                ('plano', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Plano de Trabalho')),
                ('referencia', models.TextField(max_length=2000, verbose_name='Referências em ABNT (5 obras ou 2000 caracteres)')),
                ('bolsista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bolsista', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ManyToManyField(blank=True, help_text='Para selecionar ou deselecionar um colaborador pressione CTRL + Botão Esquerdo do mouse ou Command + Botão Esquerdo do mouse', null=True, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
                ('edital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edital.Edital')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['titulo', 'responsavel'],
            },
        ),
    ]
