# Generated by Django 2.2.1 on 2019-05-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='contato_empresa',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email da empresa'),
        ),
    ]
