# Generated by Django 2.2.2 on 2019-08-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0005_auto_20190705_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_a1_cinco_autores',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_a1_mais_cinco_autores_demais',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_a1_mais_cinco_autores_primeiro_ultimo',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_a2_cinco_autores',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_a2_mais_cinco_autores_demais',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_a2_mais_cinco_autores_primeiro_ultimo',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_b1_b2_cinco_autores',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_b1_b2_mais_cinco_autores_demais',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_b1_b2_mais_cinco_autores_primeiro_ultimo',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_b3_b4_cinco_autores',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_b3_b4_mais_cinco_autores_demais',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_b3_b4_mais_cinco_autores_primeiro_ultimo',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_b5_c_cinco_autores',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_b5_c_mais_cinco_autores_demais',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_artigos_qualis_b5_c_mais_cinco_autores_primeiro_ultimo',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_autoria_livros',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_autoria_livros_capitulos',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_licenca_direito',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_orientador_iniciacao_cientifica',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_orientador_mestrado',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_orientador_teses_doutorado',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_orientador_trabalho_final_curso',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_resumos_anais_eventos',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='pc_trabalhos_anais_eventos',
        ),
    ]
