# Generated by Django 2.2.2 on 2020-04-15 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0006_auto_20190806_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='colaborador',
            field=models.ManyToManyField(blank=True, help_text='Para selecionar ou deselecionar um colaborador pressione CTRL + Botão Esquerdo do mouse ou Command + Botão Esquerdo do mouse', null=True, related_name='colaborador', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador(es)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='edital',
            field=models.ForeignKey(blank=True, help_text='Campo obrigatório como todos os que tiverem *', null=True, on_delete=django.db.models.deletion.PROTECT, to='edital.Edital', verbose_name='Edital vigente *'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo projeto *'),
        ),
    ]
