# Generated by Django 3.0.4 on 2020-05-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0007_auto_20200415_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='arquivo_atualizacao_pendencia_projeto',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para enviar seu projeto', null=True, upload_to='midias', verbose_name='Arquivo anexo de atualização de pendência do projeto *'),
        ),
        migrations.AddField(
            model_name='submissao',
            name='arquivo_projeto',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para enviar seu projeto', null=True, upload_to='midias', verbose_name='Arquivo anexo do projeto *'),
        ),
    ]
