# Generated by Django 3.0.4 on 2020-05-29 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0017_auto_20200529_2005'),
        ('submissao', '0009_auto_20200527_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='edital',
            field=models.ForeignKey(help_text='Campo obrigatório como todos os que tiverem *', null=True, on_delete=django.db.models.deletion.PROTECT, to='edital.Edital', verbose_name='Edital vigente *'),
        ),
    ]
