# Generated by Django 3.0.4 on 2020-06-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_auto_20200617_2000'),
        ('edital', '0021_auto_20200615_1826'),
        ('submissao', '0013_auto_20200616_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='edital',
            field=models.ForeignKey(help_text='Campo obrigatório como todos os que tiverem *', null=True, on_delete=django.db.models.deletion.PROTECT, to='edital.Edital', verbose_name='Edital vigente *'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='programa.Programa', verbose_name='Programa ou linha do edital *'),
        ),
    ]
