# Generated by Django 3.0.4 on 2020-06-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0014_auto_20200618_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='cnpj_instituicao_beneficiada',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ da instituição beneficiada'),
        ),
        migrations.AddField(
            model_name='submissao',
            name='contato_instituicao_beneficiada',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email da instituição beneficiada'),
        ),
        migrations.AddField(
            model_name='submissao',
            name='nome_instituicao_beneficiada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da instituição beneficiada'),
        ),
    ]
