# Generated by Django 3.0.4 on 2020-06-19 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissao', '0015_auto_20200618_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='colaborador',
            field=models.ManyToManyField(blank=True, null=True, related_name='colaborador', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador(es)'),
        ),
    ]
