# Generated by Django 3.0.4 on 2020-07-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0017_auto_20200701_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='introducao',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Introdução do projeto (3000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='metodologia',
            field=models.TextField(max_length=3000, verbose_name='Materiais e Métodos do projeto (3000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='referencia',
            field=models.TextField(max_length=3000, verbose_name='Referências em ABNT (3000 caracteres)'),
        ),
    ]
