# Generated by Django 3.0.4 on 2020-07-01 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissao', '0018_auto_20200701_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='bolsista',
            field=models.ForeignKey(blank=True, help_text='Atenção: solicite que o seu bolsista faça o cadastro no SISGEP-SADEPI', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bolsista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='introducao',
            field=models.TextField(blank=True, help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=3000, null=True, verbose_name='Introdução do projeto (3000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='metodologia',
            field=models.TextField(help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=3000, verbose_name='Materiais e Métodos do projeto (3000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='motivacao',
            field=models.TextField(help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=2000, verbose_name='Justificativa do projeto (2000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='objetivo',
            field=models.TextField(help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=2000, verbose_name='Objetivos geral e específicos do projeto (2000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='plano',
            field=models.TextField(blank=True, help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=2000, null=True, verbose_name='Plano de trabalho (2000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='referencia',
            field=models.TextField(help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=3000, verbose_name='Referências em ABNT (3000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='titulo',
            field=models.TextField(help_text='Atenção: se colar seu texto no campo, confira se ele coube no espaço!!', max_length=200, verbose_name='Título do projeto (200 caracteres)'),
        ),
    ]
