# Generated by Django 3.0.8 on 2020-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0020_auto_20200709_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='programa_extensao',
            field=models.CharField(choices=[('ATENÇÃO INTEGRAL E PROMOÇÃO À SAÚDE', 'Atenção Integral e Promoção à Saúde'), ('EDUCAÇÃO, CULTURA E COMUNICAÇÃO', 'Educação, Cultura e Comunicação'), ('DIREITOS, POLÍTICAS PÚBLICAS E DIVERSIDADE', 'Direitos, Políticas Públicas e Diversidade'), ('TECNOLOGIA, INOVAÇÃO E DESENVOLVIMENTO SUSTENTÁVEL', 'Tecnologia, Inovação e Desenvolvimento Sustentável'), ('PATRIMÔNIO CULTURAL E ECONOMIA CRIATIVA', 'Patrimônio Cultural e Economia Criativa'), ('SOCIEDADE E MEIO AMBIENTE', 'Sociedade e Meio Ambiente')], default='Outro', max_length=55, verbose_name='Programa Institucional de Extensão'),
            preserve_default=False,
        ),
    ]
