# Generated by Django 3.0.8 on 2020-07-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0021_submissao_programa_extensao'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='arquivo_apendice1',
            field=models.FileField(blank=True, help_text='Use este recurso em formato de imagem (.png ou .jpeg)', null=True, upload_to='midias', verbose_name='Arquivo de apêndice ao projeto. Pode ser para ajudar na ilustração de algum processo metodológico ou para plano de trabalho.'),
        ),
    ]
