# Generated by Django 3.0.8 on 2020-07-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0024_auto_20200727_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='programa_extensao',
            field=models.CharField(blank=True, choices=[('ATENÇÃO INTEGRAL E PROMOÇÃO À SAÚDE', 'Atenção Integral e Promoção à Saúde'), ('EDUCAÇÃO, CULTURA E COMUNICAÇÃO', 'Educação, Cultura e Comunicação'), ('DIREITOS, POLÍTICAS PÚBLICAS E DIVERSIDADE', 'Direitos, Políticas Públicas e Diversidade'), ('TECNOLOGIA, INOVAÇÃO E DESENVOLVIMENTO SUSTENTÁVEL', 'Tecnologia, Inovação e Desenvolvimento Sustentável'), ('PATRIMÔNIO CULTURAL E ECONOMIA CRIATIVA', 'Patrimônio Cultural e Economia Criativa'), ('SOCIEDADE E MEIO AMBIENTE', 'Sociedade e Meio Ambiente')], max_length=55, null=True, verbose_name='Programa Institucional de Extensão'),
        ),
    ]
