# Generated by Django 2.2.1 on 2019-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area_conhecimento_cnpq',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Área de conhecimento no CNPq'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso_graduacao_vinculado',
            field=models.CharField(blank=True, help_text='Nome do curso que está lotado', max_length=50, null=True, verbose_name='Curso de graduação vinculado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso_pos_graduacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Curso de pós-graduação onde orienta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo_pesquisa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo de pesquisa vinculado'),
        ),
    ]
