# Generated by Django 2.2.1 on 2019-06-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190619_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curso_pos_graduacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Curso de pós-graduação em que orienta'),
        ),
    ]
