# Generated by Django 2.2.2 on 2019-08-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20190806_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='total_producoes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
    ]
