# Generated by Django 2.2.2 on 2019-09-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_total_producoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curso_pos_graduacao',
            field=models.CharField(blank=True, help_text='Caso esteja vinculado', max_length=50, null=True, verbose_name='Curso de pós-graduação em que orienta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo_pesquisa',
            field=models.CharField(blank=True, help_text='Caso esteja vinculado', max_length=100, null=True, verbose_name='Grupo de pesquisa vinculado'),
        ),
    ]
