# Generated by Django 2.2.2 on 2019-09-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20190910_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curso_graduacao_vinculado',
            field=models.CharField(help_text='Nome do curso que está lotado', max_length=50, verbose_name='Curso de graduação vinculado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lattes',
            field=models.CharField(max_length=100, verbose_name='Lattes'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Matrícula'),
        ),
    ]
