# Generated by Django 2.2.2 on 2020-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20190910_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash'),
        ),
    ]
