# Generated by Django 2.2.2 on 2020-04-15 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_usuario_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instituicao.Instituicao', verbose_name='Instituição'),
        ),
    ]
