# Generated by Django 3.0.4 on 2020-06-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20200531_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(help_text='Atenção: SOMENTE OS NÚMEROS', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.IntegerField(help_text='Atenção: SOMENTE OS NÚMEROS', verbose_name='RG'),
        ),
    ]
