# Generated by Django 3.0.4 on 2020-06-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20200531_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(help_text='Atenção: SOMENTE OS NÚMEROS', max_length=10, verbose_name='RG'),
        ),
    ]
