# Generated by Django 3.0.4 on 2020-06-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_auto_20200612_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area_conhecimento_cnpq',
            field=models.CharField(choices=[('CIÊNCIAS DA SAÚDE', 'Ciências da Saúde'), ('CIÊNCIAS HUMANAS', 'Ciências Humanas'), ('CIÊNCIAS SOCIAIS', 'Ciências Sociais'), ('CIÊNCIAS TECNOLÓGICAS', 'Ciências Tecnológicas')], max_length=50, verbose_name='Área de conhecimento'),
        ),
    ]
