# Generated by Django 3.0.4 on 2020-06-30 00:12

import django.contrib.auth.models
from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_auto_20200624_1549'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('professores', usuario.models.ProfessorAtivoManager()),
                ('bolsistas', usuario.models.BolsistaAtivoManager()),
                ('bolsistas_inativos', usuario.models.BolsistaInativoManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area_conhecimento_cnpq',
            field=models.CharField(choices=[('CIÊNCIAS DA SAÚDE', 'Ciências da Saúde'), ('CIÊNCIAS HUMANAS', 'Ciências Humanas'), ('CIÊNCIAS SOCIAIS', 'Ciências Sociais'), ('CIÊNCIAS TECNOLÓGICAS', 'Ciências Tecnológicas')], max_length=50, verbose_name='Área de conhecimento *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(help_text='ATENÇÃO: Somente os NÚMEROS', max_length=14, verbose_name='CPF *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='curso_graduacao_vinculado',
            field=models.CharField(help_text='Nome do curso que está lotado', max_length=50, verbose_name='Curso de Graduação vinculado *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Se ativo, o usuário tem permissão para acessar o sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lattes',
            field=models.CharField(max_length=100, verbose_name='Lattes *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome completo *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(help_text='ATENÇÃO: Somente os NÚMEROS', max_length=10, verbose_name='RG *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('PROFESSOR', 'Professor'), ('BOLSISTA', 'Bolsista')], default='PROFESSOR', help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do usuário *'),
        ),
    ]
