# Generated by Django 3.0.8 on 2020-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_auto_20200702_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='lattes',
            field=models.CharField(help_text="Clique <a href='http://buscatextual.cnpq.br/buscatextual' target='_blank'> aqui </a> para descobrir", max_length=100, verbose_name='Lattes *'),
        ),
    ]
