# Generated by Django 2.2.2 on 2020-04-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='arquivo_resposta_comissao',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', upload_to='midias', verbose_name='Arquivo padrão de resposta a submissão do projeto *'),
        ),
    ]
