# Generated by Django 3.0.4 on 2020-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0002_auto_20200415_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='arquivo_resposta_comissao',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo padrão de resposta a submissão do projeto *'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='parecer_comissao',
            field=models.TextField(max_length=2000, verbose_name='Parecer da comissão (2000 caracteres)'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='status',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EM ANÁLISE', 'Em análise')], max_length=25, null=True, verbose_name='Status do projeto'),
        ),
    ]
