# Generated by Django 3.0.4 on 2020-04-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0003_auto_20200421_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='arquivo_resposta_comissao',
            field=models.FileField(help_text='Use arquivo .pdf para a resposta', upload_to='midias', verbose_name='Arquivo padrão de resposta a submissão do projeto *'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EM ANÁLISE', 'Em análise')], max_length=25, verbose_name='Status do projeto'),
        ),
    ]
