# Generated by Django 3.0.4 on 2020-05-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0004_auto_20200421_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='arquivo_parecer_comissao_pendencia',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo de parecer depois das correções solicitadas pela comissão'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('PENDENTE', 'Pendente')], max_length=25, verbose_name='Status do projeto'),
        ),
    ]
