# Generated by Django 3.0.4 on 2020-07-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0005_auto_20200527_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comissao',
            old_name='arquivo_parecer_comissao_pendencia',
            new_name='arquivo_parecer_comissao_final',
        ),
        migrations.AlterField(
            model_name='comissao',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], max_length=25, verbose_name='Status do projeto'),
        ),
    ]
