# Generated by Django 3.0.4 on 2020-07-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0007_auto_20200706_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissao',
            name='arquivo_resposta_comissao',
        ),
    ]
