# Generated by Django 3.0.4 on 2020-07-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0008_remove_comissao_arquivo_resposta_comissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comissao',
            options={'ordering': ['avaliacao_comissao', 'dt_avaliacao_comissao']},
        ),
        migrations.RemoveField(
            model_name='comissao',
            name='parecer_comissao',
        ),
        migrations.RemoveField(
            model_name='comissao',
            name='status',
        ),
        migrations.AlterField(
            model_name='comissao',
            name='arquivo_parecer_comissao_final',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo de parecer SADEPI'),
        ),
    ]
