# Generated by Django 3.0.4 on 2020-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0009_auto_20200707_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comissao',
            options={'ordering': ['avaliacao_comissao', 'status', 'dt_avaliacao_comissao']},
        ),
        migrations.AddField(
            model_name='comissao',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EM ANÁLISE', 'Em análise')], default='EM ANÁLISE', max_length=25, verbose_name='Status final do projeto'),
        ),
    ]
