# Generated by Django 3.0.4 on 2020-09-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0033_auto_20200902_1530'),
        ('comissao', '0011_auto_20200901_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='avaliacao_comissao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='avaliacao.Avaliacao', verbose_name='Selecione uma avaliação de projeto submetido para parecer da comissão *'),
        ),
    ]
